### ISSUE TITLE
Miss spelling at LDAPAUTH variables.

### ISSUE THREAD

**Issue by surauki** [k3a/yourls-ldap-plugin#13]
It's so tiny issues. I'm sorry...
I found miss spelling in plugin.php when setting port variables.

* plugin.php
```
function ldapauth_environment_check() {
	$required_params = array(
		'LDAPAUTH_HOST', // ldap host
		//'LDAAUTHP_PORT', // ldap port
		'LDAPAUTH_BASE', // base ldap path
		//'LDAPAUTH_USERNAME_FIELD', // field to check the username against
	);
```

* Incorrect
//'LDAAUTHP_PORT', // ldap port

* Correct
//'LDAPAUTH_PORT', // ldap port

that all. thank you developing !

**Comment by k3a** [comment]
Minor but why not fix it. Thanks for reporting! :)
