### ISSUE TITLE
can I use this standalone with out the cas plugin?

### ISSUE THREAD

**Issue by stpha6** [k3a/yourls-ldap-plugin#2]
hello!
Can I use this plugin without using the cas plugin along with it?  In  your usage section, it seems as if it will only work as a failover if cas fails to authenticate a user.  Is this the case, or can I use this plugin to authenticate with LDAP without using cas? 

Thanks!

**Comment by orosi** [comment]
hi all 
I have the same problems with the Stealing cookies?
but this workaroung do not work for me 
do you have any other advises to fix this problem? 
thanks a lot

**Comment by k3a** [comment]
This should be fixed with the latest commit.
