### ISSUE TITLE
Authorized Admins List

### ISSUE THREAD

**Issue by pjaydev** [k3a/yourls-ldap-plugin#23]
The options `LDAPAUTH_ALL_USERS_ADMIN = false` and `$ldapauth_authorized_admins=array( <usernames> )` are probably not documented because they are not yet working properly: When logging in with an LDAP user, whose name is not in the authorized admins list, the login will still succeed, and no logout-Link will be displayed on the admin page.

I could fix this behaviour by replacing line 157:

    return $username.' is not admin user.';

by:

    return $value;

I think, returning an error message instead of a boolean return value was not the inteded way.

**Comment by k3a** [comment]
Thanks, you are right! That function must return boolean type. I've fixed it in the master.
