### ISSUE TITLE
problem binding ldap server from synology

### ISSUE THREAD

**Issue by NemoZho** [k3a/yourls-ldap-plugin#27]
I had a synology server with a ldap server activating , and a router with port 389,636 opening and point to the ip of ldap server.
But when I tried to use this plugin , it always die at the ldap_bind process.
With other applications , such like rocketchat , binding with my ldap server is successfully.
Is it because it's binding from outside?Because my yourls server is hosting on cloud server.
thanks!

**Comment by k3a** [comment]
This looks like connectivity problem. Check you can access LDAP server from the machine executing PHP scripts, check addresses, ports, ACL rules. Look into PHP and LDAP logs, eventually run tcpdump to verify the connection is made on the LDAP side.

Hard to tell the exact cause but a lot of people use this plugin and it should not die on ldap_bind. I will keep this issue open this for some time in case someone else is experiencing this.

**Comment by JoaoCeni** [comment]
> This looks like connectivity problem. Check you can access LDAP server from the machine executing PHP scripts, check addresses, ports, ACL rules. Look into PHP and LDAP logs, eventually run tcpdump to verify the connection is made on the LDAP side.
> 
> Hard to tell the exact cause but a lot of people use this plugin and it should not die on ldap_bind. I will keep this issue open this for some time in case someone else is experiencing this.

I myself am experiencing the following problem whenever I activate this plugin:

Fatal error: Uncaught Error: Call to undefined function ldap_connect() in /var/www/html/user/plugins/yourls-ldap-plugin/plugin.php

the full error is:
Fatal error: Uncaught Error: Call to undefined function ldap_connect() in /var/www/html/user/plugins/yourls-ldap-plugin/plugin.php:126 Stack trace: #0 /var/www/html/user/plugins/yourls-ldap-plugin/plugin.php(176): ldapauth_get_ldap_connection() #1 /var/www/html/includes/functions-plugins.php(150): ldapauth_is_valid_user(false) #2 /var/www/html/includes/functions-auth.php(71): yourls_apply_filter('is_valid_user', false) #3 /var/www/html/includes/auth.php(5): yourls_is_valid_user() #4 /var/www/html/includes/functions.php(1318): require_once('/var/www/html/i...') #5 /var/www/html/admin/index.php(4): yourls_maybe_require_auth() #6 {main} thrown in /var/www/html/user/plugins/yourls-ldap-plugin/plugin.php on line 126

tried yourls 1.7.3 and latest...Docker version 23.0.5, build bc4487a

**Comment by k3a** [comment]
@JoaoCeni `Call to undefined function ldap_connect()` is unrelated to this issue. It says your PHP has no support for LDAP built in. See [PHP manual](https://www.php.net/manual/en/ldap.installation.php)
